[platformio]
default_envs = esp32s3_ili9488

[env:esp32s3_ili9488]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv

; Jeżeli Twoja płytka nie ma PSRAM, zakomentuj dwie linie poniżej.
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DEVO3_PLATFORMIO_V12_FULL_PANELS=1
    -DEVO_PANEL_ILI9488_NATIVE=1
    -DEVO_V12_PANEL_UI=1
    -DUSER_SETUP_LOADED=1

lib_deps =
    lovyan03/LovyanGFX@^1.2.20
    olikraus/U8g2
    tzapu/WiFiManager
    me-no-dev/AsyncTCP
    me-no-dev/ESP Async WebServer
    bblanchon/ArduinoJson
    ESP32-audioI2S

lib_ignore =
    Audio

build_src_filter =
    +<*>
    -<main_EVO3_ORIGINAL_BACKUP.cpp.txt>
